const List<Map<String, dynamic>> kQuranSurahs = [
  {'number': 1, 'name': 'الفاتحة', 'english': 'Al-Fatihah', 'type': 'meccan', 'verses': 7, 'juz': 1},
  {'number': 2, 'name': 'البقرة', 'english': 'Al-Baqarah', 'type': 'medinan', 'verses': 286, 'juz': 1},
  {'number': 3, 'name': 'آل عمران', 'english': 'Ali Imran', 'type': 'medinan', 'verses': 200, 'juz': 3},
  {'number': 4, 'name': 'النساء', 'english': 'An-Nisa', 'type': 'medinan', 'verses': 176, 'juz': 4},
  {'number': 5, 'name': 'المائدة', 'english': 'Al-Maidah', 'type': 'medinan', 'verses': 120, 'juz': 6},
  {'number': 6, 'name': 'الأنعام', 'english': 'Al-Anam', 'type': 'meccan', 'verses': 165, 'juz': 7},
  {'number': 7, 'name': 'الأعراف', 'english': 'Al-Araf', 'type': 'meccan', 'verses': 206, 'juz': 8},
  {'number': 8, 'name': 'الأنفال', 'english': 'Al-Anfal', 'type': 'medinan', 'verses': 75, 'juz': 9},
  {'number': 9, 'name': 'التوبة', 'english': 'At-Tawbah', 'type': 'medinan', 'verses': 129, 'juz': 10},
  {'number': 10, 'name': 'يونس', 'english': 'Yunus', 'type': 'meccan', 'verses': 109, 'juz': 11},
  {'number': 11, 'name': 'هود', 'english': 'Hud', 'type': 'meccan', 'verses': 123, 'juz': 11},
  {'number': 12, 'name': 'يوسف', 'english': 'Yusuf', 'type': 'meccan', 'verses': 111, 'juz': 12},
  {'number': 13, 'name': 'الرعد', 'english': 'Ar-Rad', 'type': 'medinan', 'verses': 43, 'juz': 13},
  {'number': 14, 'name': 'إبراهيم', 'english': 'Ibrahim', 'type': 'meccan', 'verses': 52, 'juz': 13},
  {'number': 15, 'name': 'الحجر', 'english': 'Al-Hijr', 'type': 'meccan', 'verses': 99, 'juz': 14},
  {'number': 16, 'name': 'النحل', 'english': 'An-Nahl', 'type': 'meccan', 'verses': 128, 'juz': 14},
  {'number': 17, 'name': 'الإسراء', 'english': 'Al-Isra', 'type': 'meccan', 'verses': 111, 'juz': 15},
  {'number': 18, 'name': 'الكهف', 'english': 'Al-Kahf', 'type': 'meccan', 'verses': 110, 'juz': 15},
  {'number': 19, 'name': 'مريم', 'english': 'Maryam', 'type': 'meccan', 'verses': 98, 'juz': 16},
  {'number': 20, 'name': 'طه', 'english': 'Taha', 'type': 'meccan', 'verses': 135, 'juz': 16},
  {'number': 21, 'name': 'الأنبياء', 'english': 'Al-Anbiya', 'type': 'meccan', 'verses': 112, 'juz': 17},
  {'number': 22, 'name': 'الحج', 'english': 'Al-Hajj', 'type': 'medinan', 'verses': 78, 'juz': 17},
  {'number': 23, 'name': 'المؤمنون', 'english': 'Al-Muminun', 'type': 'meccan', 'verses': 118, 'juz': 18},
  {'number': 24, 'name': 'النور', 'english': 'An-Nur', 'type': 'medinan', 'verses': 64, 'juz': 18},
  {'number': 25, 'name': 'الفرقان', 'english': 'Al-Furqan', 'type': 'meccan', 'verses': 77, 'juz': 18},
  {'number': 26, 'name': 'الشعراء', 'english': 'Ash-Shuara', 'type': 'meccan', 'verses': 227, 'juz': 19},
  {'number': 27, 'name': 'النمل', 'english': 'An-Naml', 'type': 'meccan', 'verses': 93, 'juz': 19},
  {'number': 28, 'name': 'القصص', 'english': 'Al-Qasas', 'type': 'meccan', 'verses': 88, 'juz': 20},
  {'number': 29, 'name': 'العنكبوت', 'english': 'Al-Ankabut', 'type': 'meccan', 'verses': 69, 'juz': 20},
  {'number': 30, 'name': 'الروم', 'english': 'Ar-Rum', 'type': 'meccan', 'verses': 60, 'juz': 21},
  {'number': 31, 'name': 'لقمان', 'english': 'Luqman', 'type': 'meccan', 'verses': 34, 'juz': 21},
  {'number': 32, 'name': 'السجدة', 'english': 'As-Sajdah', 'type': 'meccan', 'verses': 30, 'juz': 21},
  {'number': 33, 'name': 'الأحزاب', 'english': 'Al-Ahzab', 'type': 'medinan', 'verses': 73, 'juz': 21},
  {'number': 34, 'name': 'سبأ', 'english': 'Saba', 'type': 'meccan', 'verses': 54, 'juz': 22},
  {'number': 35, 'name': 'فاطر', 'english': 'Fatir', 'type': 'meccan', 'verses': 45, 'juz': 22},
  {'number': 36, 'name': 'يس', 'english': 'Yaseen', 'type': 'meccan', 'verses': 83, 'juz': 22},
  {'number': 37, 'name': 'الصافات', 'english': 'As-Saffat', 'type': 'meccan', 'verses': 182, 'juz': 23},
  {'number': 38, 'name': 'ص', 'english': 'Sad', 'type': 'meccan', 'verses': 88, 'juz': 23},
  {'number': 39, 'name': 'الزمر', 'english': 'Az-Zumar', 'type': 'meccan', 'verses': 75, 'juz': 23},
  {'number': 40, 'name': 'غافر', 'english': 'Ghafir', 'type': 'meccan', 'verses': 85, 'juz': 24},
  {'number': 41, 'name': 'فصلت', 'english': 'Fussilat', 'type': 'meccan', 'verses': 54, 'juz': 24},
  {'number': 42, 'name': 'الشورى', 'english': 'Ash-Shura', 'type': 'meccan', 'verses': 53, 'juz': 25},
  {'number': 43, 'name': 'الزخرف', 'english': 'Az-Zukhruf', 'type': 'meccan', 'verses': 89, 'juz': 25},
  {'number': 44, 'name': 'الدخان', 'english': 'Ad-Dukhan', 'type': 'meccan', 'verses': 59, 'juz': 25},
  {'number': 45, 'name': 'الجاثية', 'english': 'Al-Jathiyah', 'type': 'meccan', 'verses': 37, 'juz': 25},
  {'number': 46, 'name': 'الأحقاف', 'english': 'Al-Ahqaf', 'type': 'meccan', 'verses': 35, 'juz': 26},
  {'number': 47, 'name': 'محمد', 'english': 'Muhammad', 'type': 'medinan', 'verses': 38, 'juz': 26},
  {'number': 48, 'name': 'الفتح', 'english': 'Al-Fath', 'type': 'medinan', 'verses': 29, 'juz': 26},
  {'number': 49, 'name': 'الحجرات', 'english': 'Al-Hujurat', 'type': 'medinan', 'verses': 18, 'juz': 26},
  {'number': 50, 'name': 'ق', 'english': 'Qaf', 'type': 'meccan', 'verses': 45, 'juz': 26},
  {'number': 51, 'name': 'الذاريات', 'english': 'Adh-Dhariyat', 'type': 'meccan', 'verses': 60, 'juz': 26},
  {'number': 52, 'name': 'الطور', 'english': 'At-Tur', 'type': 'meccan', 'verses': 49, 'juz': 27},
  {'number': 53, 'name': 'النجم', 'english': 'An-Najm', 'type': 'meccan', 'verses': 62, 'juz': 27},
  {'number': 54, 'name': 'القمر', 'english': 'Al-Qamar', 'type': 'meccan', 'verses': 55, 'juz': 27},
  {'number': 55, 'name': 'الرحمن', 'english': 'Ar-Rahman', 'type': 'medinan', 'verses': 78, 'juz': 27},
  {'number': 56, 'name': 'الواقعة', 'english': 'Al-Waqiah', 'type': 'meccan', 'verses': 96, 'juz': 27},
  {'number': 57, 'name': 'الحديد', 'english': 'Al-Hadid', 'type': 'medinan', 'verses': 29, 'juz': 27},
  {'number': 58, 'name': 'المجادلة', 'english': 'Al-Mujadila', 'type': 'medinan', 'verses': 22, 'juz': 28},
  {'number': 59, 'name': 'الحشر', 'english': 'Al-Hashr', 'type': 'medinan', 'verses': 24, 'juz': 28},
  {'number': 60, 'name': 'الممتحنة', 'english': 'Al-Mumtahanah', 'type': 'medinan', 'verses': 13, 'juz': 28},
  {'number': 61, 'name': 'الصف', 'english': 'As-Saff', 'type': 'medinan', 'verses': 14, 'juz': 28},
  {'number': 62, 'name': 'الجمعة', 'english': 'Al-Jumuah', 'type': 'medinan', 'verses': 11, 'juz': 28},
  {'number': 63, 'name': 'المنافقون', 'english': 'Al-Munafiqun', 'type': 'medinan', 'verses': 11, 'juz': 28},
  {'number': 64, 'name': 'التغابن', 'english': 'At-Taghabun', 'type': 'medinan', 'verses': 18, 'juz': 28},
  {'number': 65, 'name': 'الطلاق', 'english': 'At-Talaq', 'type': 'medinan', 'verses': 12, 'juz': 28},
  {'number': 66, 'name': 'التحريم', 'english': 'At-Tahrim', 'type': 'medinan', 'verses': 12, 'juz': 28},
  {'number': 67, 'name': 'الملك', 'english': 'Al-Mulk', 'type': 'meccan', 'verses': 30, 'juz': 29},
  {'number': 68, 'name': 'القلم', 'english': 'Al-Qalam', 'type': 'meccan', 'verses': 52, 'juz': 29},
  {'number': 69, 'name': 'الحاقة', 'english': 'Al-Haqqah', 'type': 'meccan', 'verses': 52, 'juz': 29},
  {'number': 70, 'name': 'المعارج', 'english': 'Al-Maarij', 'type': 'meccan', 'verses': 44, 'juz': 29},
  {'number': 71, 'name': 'نوح', 'english': 'Nuh', 'type': 'meccan', 'verses': 28, 'juz': 29},
  {'number': 72, 'name': 'الجن', 'english': 'Al-Jinn', 'type': 'meccan', 'verses': 28, 'juz': 29},
  {'number': 73, 'name': 'المزمل', 'english': 'Al-Muzzammil', 'type': 'meccan', 'verses': 20, 'juz': 29},
  {'number': 74, 'name': 'المدثر', 'english': 'Al-Muddaththir', 'type': 'meccan', 'verses': 56, 'juz': 29},
  {'number': 75, 'name': 'القيامة', 'english': 'Al-Qiyamah', 'type': 'meccan', 'verses': 40, 'juz': 29},
  {'number': 76, 'name': 'الإنسان', 'english': 'Al-Insan', 'type': 'medinan', 'verses': 31, 'juz': 29},
  {'number': 77, 'name': 'المرسلات', 'english': 'Al-Mursalat', 'type': 'meccan', 'verses': 50, 'juz': 29},
  {'number': 78, 'name': 'النبأ', 'english': 'An-Naba', 'type': 'meccan', 'verses': 40, 'juz': 30},
  {'number': 79, 'name': 'النازعات', 'english': 'An-Naziat', 'type': 'meccan', 'verses': 46, 'juz': 30},
  {'number': 80, 'name': 'عبس', 'english': 'Abasa', 'type': 'meccan', 'verses': 42, 'juz': 30},
  {'number': 81, 'name': 'التكوير', 'english': 'At-Takwir', 'type': 'meccan', 'verses': 29, 'juz': 30},
  {'number': 82, 'name': 'الانفطار', 'english': 'Al-Infitar', 'type': 'meccan', 'verses': 19, 'juz': 30},
  {'number': 83, 'name': 'المطففين', 'english': 'Al-Mutaffifin', 'type': 'meccan', 'verses': 36, 'juz': 30},
  {'number': 84, 'name': 'الانشقاق', 'english': 'Al-Inshiqaq', 'type': 'meccan', 'verses': 25, 'juz': 30},
  {'number': 85, 'name': 'البروج', 'english': 'Al-Buruj', 'type': 'meccan', 'verses': 22, 'juz': 30},
  {'number': 86, 'name': 'الطارق', 'english': 'At-Tariq', 'type': 'meccan', 'verses': 17, 'juz': 30},
  {'number': 87, 'name': 'الأعلى', 'english': 'Al-Ala', 'type': 'meccan', 'verses': 19, 'juz': 30},
  {'number': 88, 'name': 'الغاشية', 'english': 'Al-Ghashiyah', 'type': 'meccan', 'verses': 26, 'juz': 30},
  {'number': 89, 'name': 'الفجر', 'english': 'Al-Fajr', 'type': 'meccan', 'verses': 30, 'juz': 30},
  {'number': 90, 'name': 'البلد', 'english': 'Al-Balad', 'type': 'meccan', 'verses': 20, 'juz': 30},
  {'number': 91, 'name': 'الشمس', 'english': 'Ash-Shams', 'type': 'meccan', 'verses': 15, 'juz': 30},
  {'number': 92, 'name': 'الليل', 'english': 'Al-Layl', 'type': 'meccan', 'verses': 21, 'juz': 30},
  {'number': 93, 'name': 'الضحى', 'english': 'Ad-Duha', 'type': 'meccan', 'verses': 11, 'juz': 30},
  {'number': 94, 'name': 'الشرح', 'english': 'Ash-Sharh', 'type': 'meccan', 'verses': 8, 'juz': 30},
  {'number': 95, 'name': 'التين', 'english': 'At-Tin', 'type': 'meccan', 'verses': 8, 'juz': 30},
  {'number': 96, 'name': 'العلق', 'english': 'Al-Alaq', 'type': 'meccan', 'verses': 19, 'juz': 30},
  {'number': 97, 'name': 'القدر', 'english': 'Al-Qadr', 'type': 'meccan', 'verses': 5, 'juz': 30},
  {'number': 98, 'name': 'البينة', 'english': 'Al-Bayyinah', 'type': 'medinan', 'verses': 8, 'juz': 30},
  {'number': 99, 'name': 'الزلزلة', 'english': 'Az-Zalzalah', 'type': 'medinan', 'verses': 8, 'juz': 30},
  {'number': 100, 'name': 'العاديات', 'english': 'Al-Adiyat', 'type': 'meccan', 'verses': 11, 'juz': 30},
  {'number': 101, 'name': 'القارعة', 'english': 'Al-Qariah', 'type': 'meccan', 'verses': 11, 'juz': 30},
  {'number': 102, 'name': 'التكاثر', 'english': 'At-Takathur', 'type': 'meccan', 'verses': 8, 'juz': 30},
  {'number': 103, 'name': 'العصر', 'english': 'Al-Asr', 'type': 'meccan', 'verses': 3, 'juz': 30},
  {'number': 104, 'name': 'الهمزة', 'english': 'Al-Humazah', 'type': 'meccan', 'verses': 9, 'juz': 30},
  {'number': 105, 'name': 'الفيل', 'english': 'Al-Fil', 'type': 'meccan', 'verses': 5, 'juz': 30},
  {'number': 106, 'name': 'قريش', 'english': 'Quraysh', 'type': 'meccan', 'verses': 4, 'juz': 30},
  {'number': 107, 'name': 'الماعون', 'english': 'Al-Maun', 'type': 'meccan', 'verses': 7, 'juz': 30},
  {'number': 108, 'name': 'الكوثر', 'english': 'Al-Kawthar', 'type': 'meccan', 'verses': 3, 'juz': 30},
  {'number': 109, 'name': 'الكافرون', 'english': 'Al-Kafirun', 'type': 'meccan', 'verses': 6, 'juz': 30},
  {'number': 110, 'name': 'النصر', 'english': 'An-Nasr', 'type': 'medinan', 'verses': 3, 'juz': 30},
  {'number': 111, 'name': 'المسد', 'english': 'Al-Masad', 'type': 'meccan', 'verses': 5, 'juz': 30},
  {'number': 112, 'name': 'الإخلاص', 'english': 'Al-Ikhlas', 'type': 'meccan', 'verses': 4, 'juz': 30},
  {'number': 113, 'name': 'الفلق', 'english': 'Al-Falaq', 'type': 'meccan', 'verses': 5, 'juz': 30},
  {'number': 114, 'name': 'الناس', 'english': 'An-Nas', 'type': 'meccan', 'verses': 6, 'juz': 30},
];

const List<Map<String, dynamic>> kQuranJuzes = [
  {'number': 1, 'startText': 'الم', 'surahName': 'البقرة', 'ayah': 1},
  {'number': 2, 'startText': 'سيقول السفهاء', 'surahName': 'البقرة', 'ayah': 142},
  {'number': 3, 'startText': 'تلك الرسل', 'surahName': 'البقرة', 'ayah': 253},
  {'number': 4, 'startText': 'لن تنالوا البر', 'surahName': 'آل عمران', 'ayah': 93},
  {'number': 5, 'startText': 'والمحصنات من النساء', 'surahName': 'النساء', 'ayah': 24},
  {'number': 6, 'startText': 'لا يحب الله الجهر بالسوء', 'surahName': 'النساء', 'ayah': 148},
  {'number': 7, 'startText': 'وإذا سمعوا ما أنزل', 'surahName': 'المائدة', 'ayah': 82},
  {'number': 8, 'startText': 'ولو أننا نزلنا', 'surahName': 'الأنعام', 'ayah': 111},
  {'number': 9, 'startText': 'قال الملأ', 'surahName': 'الأعراف', 'ayah': 88},
  {'number': 10, 'startText': 'واعلموا أنما غنمتم', 'surahName': 'الأنفال', 'ayah': 41},
  {'number': 11, 'startText': 'يعتذرون إليكم', 'surahName': 'التوبة', 'ayah': 93},
  {'number': 12, 'startText': 'وما من دابة في الأرض', 'surahName': 'هود', 'ayah': 6},
  {'number': 13, 'startText': 'وما أبرئ نفسي', 'surahName': 'يوسف', 'ayah': 53},
  {'number': 14, 'startText': 'ربما يود الذين كفروا', 'surahName': 'الحجر', 'ayah': 1},
  {'number': 15, 'startText': 'سبحان الذي أسرى', 'surahName': 'الإسراء', 'ayah': 1},
  {'number': 16, 'startText': 'قال ألم أقل لك', 'surahName': 'الكهف', 'ayah': 75},
  {'number': 17, 'startText': 'اقترب للناس حسابهم', 'surahName': 'الأنبياء', 'ayah': 1},
  {'number': 18, 'startText': 'قد أفلح المؤمنون', 'surahName': 'المؤمنون', 'ayah': 1},
  {'number': 19, 'startText': 'وقال الذين لا يرجون لقاءنا', 'surahName': 'الفرقان', 'ayah': 21},
  {'number': 20, 'startText': 'فما كان جواب قومه', 'surahName': 'النمل', 'ayah': 56},
  {'number': 21, 'startText': 'ولا تجادلوا أهل الكتاب', 'surahName': 'العنكبوت', 'ayah': 46},
  {'number': 22, 'startText': 'ومن يقنت منكن لله', 'surahName': 'الأحزاب', 'ayah': 31},
  {'number': 23, 'startText': 'وما أنزلنا على قومه', 'surahName': 'يس', 'ayah': 28},
  {'number': 24, 'startText': 'فمن أظلم ممن كذب', 'surahName': 'الزمر', 'ayah': 32},
  {'number': 25, 'startText': 'إليه يرد علم الساعة', 'surahName': 'فصلت', 'ayah': 47},
  {'number': 26, 'startText': 'حم', 'surahName': 'الأحقاف', 'ayah': 1},
  {'number': 27, 'startText': 'قال فما خطبكم', 'surahName': 'الذاريات', 'ayah': 31},
  {'number': 28, 'startText': 'قد سمع الله', 'surahName': 'المجادلة', 'ayah': 1},
  {'number': 29, 'startText': 'تبارك الذي بيده الملك', 'surahName': 'الملك', 'ayah': 1},
  {'number': 30, 'startText': 'عم يتساءلون', 'surahName': 'النبأ', 'ayah': 1},
];
