import '../models/adhan_sound.dart';

/// Master catalog of 110+ Authentic Adhan sounds with categories and streaming URLs.
class AdhanData {
  static const List<String> categories = [
    'الكل',
    'الحرمان الشريفان',
    'الشام وفلسطين',
    'مصر والأزهر',
    'الخليج العربي',
    'العالم الإسلامي',
    'أصوات ندية مختارة',
  ];

  static const List<AdhanSound> allSounds = [
    AdhanSound(
      id: "iconic_makkah_ali_mullah",
      title: "أذان الحرم المكي الشريف (الشهير)",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الشيخ علي أحمد ملا (شيخ مؤذني الحرم المكي)",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan1.mp3",
      durationSeconds: 218,
    ),
    AdhanSound(
      id: "iconic_madinah_surayhi",
      title: "أذان المسجد النبوي الشريف الخاشع",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الشيخ عبد المجيد السريحي",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan2.mp3",
      durationSeconds: 225,
    ),
    AdhanSound(
      id: "iconic_alaqsa_blessed",
      title: "أذان المسجد الأقصى المبارك",
      category: "الشام وفلسطين",
      muezzinOrLocation: "مؤذنو المسجد الأقصى والقدس الشريف",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan3.mp3",
      durationSeconds: 205,
    ),
    AdhanSound(
      id: "iconic_umayyad_damascus",
      title: "أذان جامع بني أمية الكبير بدمشق",
      category: "الشام وفلسطين",
      muezzinOrLocation: "الأذان الدمشقي الموحد - مقام الحجاز",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/065--.mp3",
      durationSeconds: 253,
    ),
    AdhanSound(
      id: "iconic_abdulbasit",
      title: "أذان تاريخي مجود",
      category: "مصر والأزهر",
      muezzinOrLocation: "فضيلة الشيخ عبد الباسط عبد الصمد",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan4.mp3",
      durationSeconds: 215,
    ),
    AdhanSound(
      id: "iconic_alafasy",
      title: "أذان الكويت الخاشع",
      category: "الخليج العربي",
      muezzinOrLocation: "الشيخ مشاري بن راشد العفاسي",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan5.mp3",
      durationSeconds: 240,
    ),
    AdhanSound(
      id: "iconic_alminshawi",
      title: "أذان ندي خاشع ونادر",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ محمد صديق المنشاوي",
      audioUrl: "https://archive.org/download/AlminshawiLibyaAlAnam1245/azan-minshawi.mp3",
      durationSeconds: 220,
    ),
    AdhanSound(
      id: "iconic_alhusary",
      title: "أذان القاهرة ومسجد الحسين",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ محمود خليل الحصري",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/044--.mp3",
      durationSeconds: 160,
    ),
    AdhanSound(
      id: "iconic_qatami",
      title: "أذان حجازي مؤثر",
      category: "الخليج العربي",
      muezzinOrLocation: "الشيخ ناصر القطامي",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan6.mp3",
      durationSeconds: 198,
    ),
    AdhanSound(
      id: "iconic_salimi",
      title: "أذان خاشع وباكي",
      category: "الخليج العربي",
      muezzinOrLocation: "الشيخ منصور السالمي",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan7.mp3",
      durationSeconds: 210,
    ),
    AdhanSound(
      id: "iconic_refaat",
      title: "أذان الإذاعة المصرية التاريخي",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ محمد رفعت (قيثارة السماء)",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/042--.mp3",
      durationSeconds: 235,
    ),
    AdhanSound(
      id: "iconic_mustafa_ismail",
      title: "أذان المقامات الصباحية",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ مصطفى إسماعيل",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/068-.mp3",
      durationSeconds: 200,
    ),
    AdhanSound(
      id: "iconic_turkey",
      title: "أذان إسطنبول (مقام الرست)",
      category: "العالم الإسلامي",
      muezzinOrLocation: "مؤذنو مساجد إسطنبول وتركيا",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan8.mp3",
      durationSeconds: 220,
    ),
    AdhanSound(
      id: "iconic_farouq_hadrawi",
      title: "أذان مكة المكرمة الفجري",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الشيخ فاروق عبد الرحمن حضراوي",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan9.mp3",
      durationSeconds: 230,
    ),
    AdhanSound(
      id: "iconic_algeria",
      title: "أذان المغرب العربي والجزائر",
      category: "العالم الإسلامي",
      muezzinOrLocation: "أذان على الطريقة الأندلسية والمغاربية",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan10.mp3",
      durationSeconds: 195,
    ),
    AdhanSound(
      id: "iconic_malaysia",
      title: "أذان كوالالمبور ومسجد بوترا",
      category: "العالم الإسلامي",
      muezzinOrLocation: "أذان مساجد ماليزيا",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan11.mp3",
      durationSeconds: 230,
    ),
    AdhanSound(
      id: "iconic_tunisia",
      title: "أذان جامع الزيتونة المعمور",
      category: "العالم الإسلامي",
      muezzinOrLocation: "تونس الخضراء",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan12.mp3",
      durationSeconds: 175,
    ),
    AdhanSound(
      id: "iconic_dubai",
      title: "أذان دبي والإمارات",
      category: "الخليج العربي",
      muezzinOrLocation: "مساجد دولة الإمارات العربية المتحدة",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan13.mp3",
      durationSeconds: 267,
    ),
    AdhanSound(
      id: "iconic_qatar",
      title: "أذان الدوحة ومسجد الإمام عبد الوهاب",
      category: "الخليج العربي",
      muezzinOrLocation: "مساجد دولة قطر",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan14.mp3",
      durationSeconds: 210,
    ),
    AdhanSound(
      id: "iconic_oman",
      title: "أذان جامع السلطان قابوس الأكبر",
      category: "الخليج العربي",
      muezzinOrLocation: "مسقط - سلطنة عمان",
      audioUrl: "https://www.islamcan.com/audio/adhan/azan15.mp3",
      durationSeconds: 185,
    ),
    AdhanSound(
      id: "iconic_rajhi",
      title: "أذان جامع الراجحي الكبير بالرياض",
      category: "الخليج العربي",
      muezzinOrLocation: "مؤذن جامع الراجحي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/089-1.mp3",
      durationSeconds: 176,
    ),
    AdhanSound(
      id: "azan_ia_1",
      title: "الأذان الشيخ حمزة الحلبية",
      category: "الشام وفلسطين",
      muezzinOrLocation: "الشيخ حمزة الحلبية",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/001-.mp3",
      durationSeconds: 257,
    ),
    AdhanSound(
      id: "azan_ia_2",
      title: "أحمد العمادي قطر",
      category: "الخليج العربي",
      muezzinOrLocation: "الشيخ أحمد العمادي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/002--.mp3",
      durationSeconds: 222,
    ),
    AdhanSound(
      id: "azan_ia_3",
      title: "أذان الكــويت",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/003--.mp3",
      durationSeconds: 174,
    ),
    AdhanSound(
      id: "azan_ia_4",
      title: "أذان بروني دار السلام 1",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/004----1.mp3",
      durationSeconds: 238,
    ),
    AdhanSound(
      id: "azan_ia_5",
      title: "أذان بروني دار السلام 2",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/005----2.mp3",
      durationSeconds: 220,
    ),
    AdhanSound(
      id: "azan_ia_6",
      title: "أذان حسين ايرك",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/006--.mp3",
      durationSeconds: 143,
    ),
    AdhanSound(
      id: "azan_ia_7",
      title: "أذان القـــــدس",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/007--.mp3",
      durationSeconds: 214,
    ),
    AdhanSound(
      id: "azan_ia_8",
      title: "أذان الهنـــد",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/008--.mp3",
      durationSeconds: 140,
    ),
    AdhanSound(
      id: "azan_ia_9",
      title: "أذان اندونيسيا",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/009--.mp3",
      durationSeconds: 229,
    ),
    AdhanSound(
      id: "azan_ia_10",
      title: "أذان باكستان",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/010--.mp3",
      durationSeconds: 214,
    ),
    AdhanSound(
      id: "azan_ia_11",
      title: "أذان تركيا 1",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/011---1.mp3",
      durationSeconds: 210,
    ),
    AdhanSound(
      id: "azan_ia_12",
      title: "أذان تركيا 2",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/012---2.mp3",
      durationSeconds: 79,
    ),
    AdhanSound(
      id: "azan_ia_13",
      title: "أذان جـــــورجيــــأ",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/013--.mp3",
      durationSeconds: 319,
    ),
    AdhanSound(
      id: "azan_ia_14",
      title: "أذان زهير محمد طارش",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/014-.mp3",
      durationSeconds: 217,
    ),
    AdhanSound(
      id: "azan_ia_15",
      title: "أذان عجمـــــان الأمارات",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/015---.mp3",
      durationSeconds: 172,
    ),
    AdhanSound(
      id: "azan_ia_16",
      title: "أذان مكه المكرمة 2",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الحرمان الشريفان",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/016---2.mp3",
      durationSeconds: 234,
    ),
    AdhanSound(
      id: "azan_ia_17",
      title: "أذان الشيخ عبدالباسط عبدالصمـد",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ عبد الباسط عبد الصمد",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/017-_-.mp3",
      durationSeconds: 192,
    ),
    AdhanSound(
      id: "azan_ia_18",
      title: "أذان الحرم المدني",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "مؤذنو المسجد النبوي الشريف",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/018-.mp3",
      durationSeconds: 314,
    ),
    AdhanSound(
      id: "azan_ia_19",
      title: "أذان الحرم المكي 1",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "مؤذنو الحرم المكي الشريف",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/019--1.mp3",
      durationSeconds: 236,
    ),
    AdhanSound(
      id: "azan_ia_20",
      title: "أذان الحرم المكي 2",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "مؤذنو الحرم المكي الشريف",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/020--2.mp3",
      durationSeconds: 247,
    ),
    AdhanSound(
      id: "azan_ia_21",
      title: "أذان الحرم المكي محمد رمل",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الشيخ محمد خليل رمل",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/021--.mp3",
      durationSeconds: 224,
    ),
    AdhanSound(
      id: "azan_ia_22",
      title: "أذان الحرم المكي 4",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "مؤذنو الحرم المكي الشريف",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/022-4.mp3",
      durationSeconds: 242,
    ),
    AdhanSound(
      id: "azan_ia_23",
      title: "أذان الحرم المكي5",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "مؤذنو الحرم المكي الشريف",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/023-5.mp3",
      durationSeconds: 191,
    ),
    AdhanSound(
      id: "azan_ia_24",
      title: "أذان الحرم المكي6",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "مؤذنو الحرم المكي الشريف",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/024-6.mp3",
      durationSeconds: 312,
    ),
    AdhanSound(
      id: "azan_ia_25",
      title: "أذان الشيخ البهلول أبوعرقوب1",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/025-1.mp3",
      durationSeconds: 216,
    ),
    AdhanSound(
      id: "azan_ia_26",
      title: "أذان الشيخ البهلول أبوعرقوب2",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/026-2.mp3",
      durationSeconds: 233,
    ),
    AdhanSound(
      id: "azan_ia_27",
      title: "أذان العشاء الشيخ عبدالباسط عبدالصمـد",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ عبد الباسط عبد الصمد",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/027-_-.mp3",
      durationSeconds: 190,
    ),
    AdhanSound(
      id: "azan_ia_28",
      title: "أذان الفجــر الكويت 1",
      category: "الخليج العربي",
      muezzinOrLocation: "الخليج العربي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/028---1.mp3",
      durationSeconds: 242,
    ),
    AdhanSound(
      id: "azan_ia_29",
      title: "أذان الفجــر الكويت 2",
      category: "الخليج العربي",
      muezzinOrLocation: "الخليج العربي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/029---2.mp3",
      durationSeconds: 219,
    ),
    AdhanSound(
      id: "azan_ia_30",
      title: "أذان الفجر بروني دار السلام",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/030---.mp3",
      durationSeconds: 240,
    ),
    AdhanSound(
      id: "azan_ia_31",
      title: "أذان الفجــر جـــزائـر",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/031--.mp3",
      durationSeconds: 209,
    ),
    AdhanSound(
      id: "azan_ia_32",
      title: "أذان الفجر ماليزيا",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/032--.mp3",
      durationSeconds: 230,
    ),
    AdhanSound(
      id: "azan_ia_33",
      title: "أذان الفجر مكه المكرمة",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الحرمان الشريفان",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/033--.mp3",
      durationSeconds: 255,
    ),
    AdhanSound(
      id: "azan_ia_34",
      title: "أذان الفجر المدينة المنورة",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الحرمان الشريفان",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/034--.mp3",
      durationSeconds: 311,
    ),
    AdhanSound(
      id: "azan_ia_35",
      title: "أذان الفجر بصوت أحمد نعينع",
      category: "مصر والأزهر",
      muezzinOrLocation: "د. أحمد نعينع",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/035-.mp3",
      durationSeconds: 237,
    ),
    AdhanSound(
      id: "azan_ia_36",
      title: "أذان الفجر مصــــر",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/036--.mp3",
      durationSeconds: 277,
    ),
    AdhanSound(
      id: "azan_ia_37",
      title: "أذان الفجر، بصوت الأخ أحمد نواف المجلاد",
      category: "الخليج العربي",
      muezzinOrLocation: "أحمد نواف المجلاد",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/037-.mp3",
      durationSeconds: 231,
    ),
    AdhanSound(
      id: "azan_ia_38",
      title: "أذان الفجر1 الشيخ مشاري بن راشد العفاسي",
      category: "الخليج العربي",
      muezzinOrLocation: "الشيخ مشاري بن راشد العفاسي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/038-1.mp3",
      durationSeconds: 187,
    ),
    AdhanSound(
      id: "azan_ia_39",
      title: "أذان الفجر2 الشيخ مشاري بن راشد العفاسي",
      category: "الخليج العربي",
      muezzinOrLocation: "الشيخ مشاري بن راشد العفاسي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/039-2.mp3",
      durationSeconds: 289,
    ),
    AdhanSound(
      id: "azan_ia_40",
      title: "أذان القاهرة أحمد نعينع",
      category: "مصر والأزهر",
      muezzinOrLocation: "د. أحمد نعينع",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/040--.mp3",
      durationSeconds: 242,
    ),
    AdhanSound(
      id: "azan_ia_41",
      title: "أذان القاهرة عبدالباسط عبدالصمد",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ عبد الباسط عبد الصمد",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/041--.mp3",
      durationSeconds: 233,
    ),
    AdhanSound(
      id: "azan_ia_42",
      title: "أذان القاهرة محمد رفعت",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ محمد رفعت",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/042--.mp3",
      durationSeconds: 235,
    ),
    AdhanSound(
      id: "azan_ia_43",
      title: "أذان القاهرة محمد علي البنا",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ محمود علي البنا",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/043--.mp3",
      durationSeconds: 185,
    ),
    AdhanSound(
      id: "azan_ia_44",
      title: "أذان القاهرة محمود خليل الحصري",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ محمود خليل الحصري",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/044--.mp3",
      durationSeconds: 159,
    ),
    AdhanSound(
      id: "azan_ia_45",
      title: "أذان المسجد الأقصى ناجي قزاز",
      category: "الشام وفلسطين",
      muezzinOrLocation: "الشيخ ناجي قزاز",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/045--.mp3",
      durationSeconds: 217,
    ),
    AdhanSound(
      id: "azan_ia_46",
      title: "أذان المسجد الأقصى ناجي قزا",
      category: "الشام وفلسطين",
      muezzinOrLocation: "الشيخ ناجي قزاز",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/046--.mp3",
      durationSeconds: 258,
    ),
    AdhanSound(
      id: "azan_ia_47",
      title: "أذان المــلا مكه المكرمة",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الحرمان الشريفان",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/047--.mp3",
      durationSeconds: 207,
    ),
    AdhanSound(
      id: "azan_ia_48",
      title: "أذان بصوت الشيخ المنشاوي",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ محمد صديق المنشاوي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/048-.mp3",
      durationSeconds: 279,
    ),
    AdhanSound(
      id: "azan_ia_49",
      title: "أذان بصوت الشيخ عبدالباسط",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ عبد الباسط عبد الصمد",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/049-.mp3",
      durationSeconds: 279,
    ),
    AdhanSound(
      id: "azan_ia_50",
      title: "ذان بصوت الشيخ المنشاوي",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ محمد صديق المنشاوي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/050-.mp3",
      durationSeconds: 283,
    ),
    AdhanSound(
      id: "azan_ia_51",
      title: "أذان بصوت حاج سليمان مختار الجزائر",
      category: "العالم الإسلامي",
      muezzinOrLocation: "الشيخ سليمان مختار",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/051--.mp3",
      durationSeconds: 205,
    ),
    AdhanSound(
      id: "azan_ia_52",
      title: "أذان بصوت عبدالباسط عبد الصمد",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ عبد الباسط عبد الصمد",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/052-.mp3",
      durationSeconds: 277,
    ),
    AdhanSound(
      id: "azan_ia_53",
      title: "أذان عبدالكريم جباري",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/053-.mp3",
      durationSeconds: 166,
    ),
    AdhanSound(
      id: "azan_ia_54",
      title: "أذان من فلسطين بصوت صهيب هاني",
      category: "الشام وفلسطين",
      muezzinOrLocation: "القارئ صهيب هاني",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/054--.mp3",
      durationSeconds: 199,
    ),
    AdhanSound(
      id: "azan_ia_55",
      title: "أذان من مسجد الملك فهد بنجران بصوت حمـــدان المالكي",
      category: "الخليج العربي",
      muezzinOrLocation: "حمدان المالكي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/055-.mp3",
      durationSeconds: 271,
    ),
    AdhanSound(
      id: "azan_ia_56",
      title: "أذن الحرم المكي 3",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "مؤذنو الحرم المكي الشريف",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/056--3.mp3",
      durationSeconds: 278,
    ),
    AdhanSound(
      id: "azan_ia_57",
      title: "الأذان جزر المالديف",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/057--.mp3",
      durationSeconds: 218,
    ),
    AdhanSound(
      id: "azan_ia_58",
      title: "الأذان دبــي الأمارات",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/058---.mp3",
      durationSeconds: 267,
    ),
    AdhanSound(
      id: "azan_ia_59",
      title: "الأذان ماليزيا",
      category: "العالم الإسلامي",
      muezzinOrLocation: "العالم الإسلامي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/059--.mp3",
      durationSeconds: 230,
    ),
    AdhanSound(
      id: "azan_ia_60",
      title: "الأذان مسقط عمان",
      category: "الخليج العربي",
      muezzinOrLocation: "الخليج العربي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/060--.mp3",
      durationSeconds: 183,
    ),
    AdhanSound(
      id: "azan_ia_61",
      title: "الأذان السيد متولي العال لبنان",
      category: "العالم الإسلامي",
      muezzinOrLocation: "الشيخ السيد متولي عبد العال",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/061---.mp3",
      durationSeconds: 201,
    ),
    AdhanSound(
      id: "azan_ia_62",
      title: "الأذان المدينة المنورة",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "الحرمان الشريفان",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/062--.mp3",
      durationSeconds: 268,
    ),
    AdhanSound(
      id: "azan_ia_63",
      title: "الأذان تونــس",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/063--.mp3",
      durationSeconds: 176,
    ),
    AdhanSound(
      id: "azan_ia_64",
      title: "الأذان جــزائــر",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/064--.mp3",
      durationSeconds: 195,
    ),
    AdhanSound(
      id: "azan_ia_65",
      title: "الأذان سوريا",
      category: "الشام وفلسطين",
      muezzinOrLocation: "جامع بني أمية الكبير بدمشق",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/065--.mp3",
      durationSeconds: 253,
    ),
    AdhanSound(
      id: "azan_ia_66",
      title: "الأذان عبدالرزاق صالح لبنان",
      category: "العالم الإسلامي",
      muezzinOrLocation: "الشيخ عبد الرزاق صالح",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/066---.mp3",
      durationSeconds: 281,
    ),
    AdhanSound(
      id: "azan_ia_67",
      title: "الأذان مهدي البيشي",
      category: "الخليج العربي",
      muezzinOrLocation: "الخليج العربي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/067--.mp3",
      durationSeconds: 253,
    ),
    AdhanSound(
      id: "azan_ia_68",
      title: "الأذان الشيخ مصطفى إسماعيل",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ مصطفى إسماعيل",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/068-.mp3",
      durationSeconds: 200,
    ),
    AdhanSound(
      id: "azan_ia_69",
      title: "الأذان الفجر القــدس",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/069--.mp3",
      durationSeconds: 183,
    ),
    AdhanSound(
      id: "azan_ia_70",
      title: "الأذان الفجر أم القــوين",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/070--.mp3",
      durationSeconds: 222,
    ),
    AdhanSound(
      id: "azan_ia_71",
      title: "الأذان القاهرة أبو العنين شعيشع",
      category: "مصر والأزهر",
      muezzinOrLocation: "الشيخ أبو العينين شعيشع",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/071--.mp3",
      durationSeconds: 268,
    ),
    AdhanSound(
      id: "azan_ia_72",
      title: "الأذان بصوت الأخ أحمد نواف المجلاد",
      category: "الخليج العربي",
      muezzinOrLocation: "أحمد نواف المجلاد",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/072-.mp3",
      durationSeconds: 206,
    ),
    AdhanSound(
      id: "azan_ia_73",
      title: "الأذان",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/073-.mp3",
      durationSeconds: 152,
    ),
    AdhanSound(
      id: "azan_ia_74",
      title: "الأذان1 الشيخ مشاري بن راشد العفاسي",
      category: "الخليج العربي",
      muezzinOrLocation: "الشيخ مشاري بن راشد العفاسي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/074-1_-.mp3",
      durationSeconds: 241,
    ),
    AdhanSound(
      id: "azan_ia_75",
      title: "الأذان1",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/075-1.mp3",
      durationSeconds: 160,
    ),
    AdhanSound(
      id: "azan_ia_76",
      title: "الأذان2 الشيخ مشاري بن راشد العفاسي",
      category: "الخليج العربي",
      muezzinOrLocation: "الشيخ مشاري بن راشد العفاسي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/076-2_-.mp3",
      durationSeconds: 257,
    ),
    AdhanSound(
      id: "azan_ia_77",
      title: "الأذان2",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/077-2.mp3",
      durationSeconds: 213,
    ),
    AdhanSound(
      id: "azan_ia_78",
      title: "الأذان3",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/078-3.mp3",
      durationSeconds: 204,
    ),
    AdhanSound(
      id: "azan_ia_79",
      title: "الأذان4",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/079-4.mp3",
      durationSeconds: 204,
    ),
    AdhanSound(
      id: "azan_ia_80",
      title: "الأذان5",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/080-5.mp3",
      durationSeconds: 165,
    ),
    AdhanSound(
      id: "azan_ia_81",
      title: "الأذان6",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/081-6.mp3",
      durationSeconds: 182,
    ),
    AdhanSound(
      id: "azan_ia_82",
      title: "الأذان7",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/082-7.mp3",
      durationSeconds: 140,
    ),
    AdhanSound(
      id: "azan_ia_83",
      title: "الأذان8",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/083-8.mp3",
      durationSeconds: 202,
    ),
    AdhanSound(
      id: "azan_ia_84",
      title: "الأذان9",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/084-9.mp3",
      durationSeconds: 211,
    ),
    AdhanSound(
      id: "azan_ia_85",
      title: "الأذان10",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/085-10.mp3",
      durationSeconds: 238,
    ),
    AdhanSound(
      id: "azan_ia_86",
      title: "الأذان11",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/086-11.mp3",
      durationSeconds: 228,
    ),
    AdhanSound(
      id: "azan_ia_87",
      title: "الحرم المدني 2",
      category: "الحرمان الشريفان",
      muezzinOrLocation: "مؤذنو المسجد النبوي الشريف",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/087--2.mp3",
      durationSeconds: 222,
    ),
    AdhanSound(
      id: "azan_ia_88",
      title: "تكبير العيد",
      category: "أصوات ندية مختارة",
      muezzinOrLocation: "أصوات ندية مختارة",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/088-.mp3",
      durationSeconds: 100,
    ),
    AdhanSound(
      id: "azan_ia_89",
      title: "مؤذن جامع الراجحي بالرياض (1)",
      category: "الخليج العربي",
      muezzinOrLocation: "الخليج العربي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/089-1.mp3",
      durationSeconds: 176,
    ),
    AdhanSound(
      id: "azan_ia_90",
      title: "مؤذن جامع الراجحي بالرياض (2)",
      category: "الخليج العربي",
      muezzinOrLocation: "الخليج العربي",
      audioUrl: "https://archive.org/download/90---azan---90---azan--many----sound----mp3---alazan/090-2.mp3",
      durationSeconds: 181,
    ),
  ];

  static AdhanSound get defaultSound => allSounds.first;

  static AdhanSound getById(String? id) {
    if (id == null) return defaultSound;
    return allSounds.firstWhere((s) => s.id == id, orElse: () => defaultSound);
  }
}
